name: End-to-end tests
on:
 schedule:
  - cron: "35 8,11,14 * * 1-5"
  - cron: "20 9,12 * * 1-5"
  - cron: "5 10,13 * * 1-5"
  - cron: "50 10,13 * * 1-5"
  
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          spec: cypress/e2e/atpark.cy.js
